# This is a basic workflow that is manually triggered

name: Trigger host update

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # job name
  hostupdate:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: curl
      uses: wei/curl@master
      with:
        args: "-u capstone:1180ad69d34e827e11aad7e779f7d26faa http://jenkins.smilr.net/jo
b/capstone-vis/build?token=capGO"
